language: java

jdk:
  - oraclejdk8

build:
  ci:
    # Configure nexus repository settings
    - mkdir ~/.m2
    - cp settings.xml ~/.m2/.
    # Build
    - cd simple
    - mvn install
    # Copy artifcats to nexus
    - mvn deploy

resources:
  - name: nodeapp_maven_repo
    type: gitRepo
    integration: "drship_github"
    versionTemplate:
      sourceName: "ambarish2012/nodeapp_maven"
      branch: master
    
jobs:
  - name: pull_maven_dependencies
    type: runSh
    steps:
      - IN: nodeapp_maven_repo
      - TASK:
          script:
            - sudo apt-get install maven
            - mvn -version
            - pushd $(shipctl get_resource_state "nodeapp_maven_repo")
            - mkdir ~/.m2
            - cp settings.xml ~/.m2/.
            - cd simple
            - mvn dependency:resolve
            - popd
